# Generated by Django 3.0.8 on 2020-07-08 17:27

import clientes.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=11)),
                ('email', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to=clientes.models.Cliente.get_upload_handler)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=15)),
                ('cidade', models.CharField(max_length=15)),
                ('estado', models.CharField(max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.Cliente')),
            ],
        ),
    ]
